### ISSUE TITLE
сделать docker-compose с базой данных

### ISSUE THREAD

**Issue by ctrlok** [shrlok/DevOps-experience#5]
Мы хотим расширить наше приложение так чтобы оно использовало базу данных

Необходимо создать docker-compose в который добавить это приложение и бд postgresql 

Следующей задачей будет обновить приложение так чтобы оно отдавало данные из базы (потом придумаем какие)

**Comment by shrlok** [comment]
Заработало.

**Comment by shrlok** [comment]
Это ж вроде готово уже.

**Comment by ctrlok** [comment]
Мерджи pr тогда и закрывай issue
